security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: DIA\TestBundle\Entity\User, property: username }
    encoders:
        DIA\TestBundle\Entity\User: sha1

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: true
            form_login:
                check_path: login
                login_path: /
                default_target_path: blog_main
            logout:
                path:   logout
                target: DIATestBundle_homepage

    access_control:
        - { path: /blog/.*, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }