DIATestBundle_homepage:
    pattern:  /
    defaults: { _controller: DIATestBundle:Welcome:welcome}

register:
    pattern:  /register
    defaults: { _controller: DIATestBundle:Welcome:register }
register_success:
    pattern:  /registerSuccessfull
    defaults: { _controller: DIATestBundle:Welcome:regSuccess }

DIATestBundle_main:
    resource: "@DIATestBundle/Resources/config/routing/blog.yml"
    prefix:   /blog
