parameters:
#    dia_test.example.class: DIA\TestBundle\Example

services:
#    dia_test.example:
#        class: %dia_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
